#!/usr/bin/env python3
"""Panel (b): RIS profiles.  Mirror about the GB, convolve with a 1 nm FWHM
Gaussian, keep the right half.  Emits framework_b.tex (schematic, no axes)."""
import math

DX      = 0.3        # nm, grid spacing of *_final.csv
FWHM    = 1.0        # nm, Gaussian applied to match the EDX probe size
XMAX    = 8.0        # nm shown
FINE    = 0.05       # nm, resampling before the convolution (smooth curves)
CMAX    = 0.22       # top of the (unlabelled) concentration scale
W, H    = 8.60, 5.20 # cm, plot box
PAD     = 0.55       # cm of clear space below zero, so the Si line is not on the frame
TOP     = 0.40       # cm of headroom above the Cr plateau

sig = FWHM / (2 * math.sqrt(2 * math.log(2)))

def load(f):
    v = open(f).read().replace('\n', ',').split(',')
    return [float(x) for x in v if x.strip()]

def resample(y):
    n = len(y)
    m = int((n - 1) * DX / FINE) + 1
    out = []
    for i in range(m):
        t = i * FINE / DX
        j = min(int(t), n - 2)
        out.append(y[j] + (y[j + 1] - y[j]) * (t - j))
    return out

def convolve_half(y):
    """mirror about x=0, convolve, return the right half"""
    n    = len(y)
    full = [y[n - 1 - i] for i in range(n - 1)] + y
    R    = int(math.ceil(4 * sig / FINE))
    out  = []
    for i in range(n - 1, len(full)):
        num = den = 0.0
        for j in range(i - R, i + R + 1):
            k = min(max(j, 0), len(full) - 1)          # flat extension
            w = math.exp(-((j - i) * FINE) ** 2 / (2 * sig * sig))
            num += w * full[k]; den += w
        out.append(num / den)
    return out

X = lambda x_nm: x_nm / XMAX * W
Y = lambda c:    PAD + c / CMAX * (H - PAD - TOP)

curves = {}
for el in ('Cr', 'Ni', 'Si'):
    c = convolve_half(resample(load(f'{el}_final.csv')))
    pts = [(i * FINE, v) for i, v in enumerate(c) if i * FINE <= XMAX + 1e-9]
    curves[el] = pts[::4]                              # every 0.2 nm is plenty

def at(el, x_nm):
    pts = curves[el]
    for (x0, c0), (x1, c1) in zip(pts, pts[1:]):
        if x0 <= x_nm <= x1:
            return c0 + (c1 - c0) * (x_nm - x0) / (x1 - x0)
    return pts[-1][1]

BX0, BX1 = 2.5, 6.5                       # nm span used for the v_lat label
AX0, AX1 = 2.3, 5.0                       # nm span of the arrows
lo = Y(max(at('Ni', AX0), at('Ni', AX1)))  # top of the Ni curve over that span
hi = Y(min(at('Cr', AX0), at('Cr', AX1)))  # bottom of the Cr curve over that span
mid  = 0.5 * (lo + hi)
yVac, yInt = mid + 0.30, mid - 0.30

blo = Y(max(at('Si', BX0), at('Si', BX1)))  # top of the Si curve over that span
bhi = Y(min(at('Ni', BX0), at('Ni', BX1)))  # bottom of the Ni curve over that span
yLat = 0.5 * (blo + bhi)
xLat = X(0.5 * (BX0 + BX1))

def path(el):
    return ' '.join(f'({X(x):.3f},{Y(c):.3f})' for x, c in curves[el])

end = {el: curves[el][-1][1] for el in curves}

tex = rf"""% Panel (b): radiation-induced segregation.  Generated by make_panel_b.py
% Profiles: mirrored about the GB, convolved with a {FWHM:.0f} nm FWHM Gaussian,
% right half shown.  Schematic - axes deliberately omitted.
\documentclass[12pt,border=2pt,tikz]{{standalone}}

\usepackage{{amsmath}}
\newcommand{{\Vac}}{{\mathrm{{V}}}}
\newcommand{{\Int}}{{\mathrm{{I}}}}
\newcommand{{\lat}}{{\mathrm{{lat}}}}
\usetikzlibrary{{arrows.meta}}

\definecolor{{cMetal}}{{RGB}}{{214,214,211}}
\definecolor{{cEdge}}{{RGB}}{{40,40,44}}
\definecolor{{cGB}}{{RGB}}{{96,42,140}}
\definecolor{{cCr}}{{RGB}}{{17,119,51}}
\definecolor{{cNi}}{{RGB}}{{0,90,181}}
\definecolor{{cSi}}{{RGB}}{{214,96,20}}

\begin{{document}}
\begin{{tikzpicture}}[
  x=1cm,y=1cm, font=\footnotesize, color=cEdge,
  eg/.style   ={{draw=cEdge, line width=0.8pt}},
  prof/.style ={{line width=1.15pt, line join=round}},
  defect/.style={{-{{Stealth[length=5pt,width=4pt]}}, line width=1.0pt, draw=cEdge}},
]

\def\W{{{W:.2f}}}\def\H{{{H:.2f}}}

% ----- metal domain ----------------------------------------------------
\fill[cMetal,eg] (0,0) rectangle (\W,\H);

% ----- the GB: a plane that acts as a perfect defect sink ---------------
\draw[cGB,line width=2.2pt,dash pattern=on 5pt off 3pt]
      (0,-0.26) -- (0,\H+0.26);
\node[anchor=west,cGB] at (0.16,\H+0.44) {{GB: perfect defect sink}};

% ----- point-defect fluxes towards the boundary ------------------------
\draw[defect] ({X(AX1):.3f},{yVac:.3f}) -- ({X(AX0):.3f},{yVac:.3f});
\node[anchor=west] at ({X(AX1) + 0.16:.3f},{yVac:.3f}) {{Vacancies}};
\draw[defect] ({X(AX1):.3f},{yInt:.3f}) -- ({X(AX0):.3f},{yInt:.3f});
\node[anchor=west] at ({X(AX1) + 0.16:.3f},{yInt:.3f}) {{Interstitials}};

% ----- segregation profiles --------------------------------------------
\draw[prof,cCr] plot coordinates {{{path('Cr')}}};
\draw[prof,cNi] plot coordinates {{{path('Ni')}}};
\draw[prof,cSi] plot coordinates {{{path('Si')}}};

\node[align=center] at ({xLat:.3f},{yLat:.3f})
      {{Lattice velocity\\ $v_{{\lat}}^{{\mathrm{{RIS}}}}=J_{{\Vac}}-J_{{\Int}}$}};

\node[anchor=east,cCr] at (\W-0.14,{Y(end['Cr']) + 0.30:.3f}) {{Cr}};
\node[anchor=east,cNi] at (\W-0.14,{Y(end['Ni']) + 0.30:.3f}) {{Ni}};
\node[anchor=east,cSi] at (\W-0.14,{Y(end['Si']) + 0.30:.3f}) {{Si}};

\end{{tikzpicture}}
\end{{document}}
"""
open('framework_b.tex', 'w').write(tex)
print("GB values after convolution (at.%):",
      {el: round(100 * curves[el][0][1], 2) for el in curves})
print("plateaux (at.%):", {el: round(100 * end[el], 2) for el in curves})
print(f"arrow band: Ni top {lo:.2f} cm, Cr bottom {hi:.2f} cm -> arrows at "
      f"{yInt:.2f} / {yVac:.2f} cm")
print(f"v_lat band: Si top {blo:.2f} cm, Ni bottom {bhi:.2f} cm -> label at "
      f"({xLat:.2f}, {yLat:.2f}) cm")
